package roo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/entireio/external-agents/agents/entire-agent-roo/internal/protocol"
)

const (
	HookNameSessionStart = "session-start"
	HookNameTurnStart    = "turn-start"
	HookNameTurnEnd      = "turn-end"
	HookNameCompaction   = "compaction"
	HookNameSessionEnd   = "session-end"

	hooksRelDir  = ".roo"
	hooksRelFile = ".roo/hooks.json"
	hooksMarker  = "Auto-generated by Entire"
)

type RooHookPayload struct {
	Event     string          `json:"event,omitempty"`
	HookEvent string          `json:"hook_event_name,omitempty"`
	SessionID string          `json:"session_id,omitempty"`
	TaskID    string          `json:"taskId,omitempty"`
	Message   string          `json:"message,omitempty"`
	Prompt    string          `json:"prompt,omitempty"`
	ToolName  string          `json:"tool_name,omitempty"`
	ToolInput json.RawMessage `json:"tool_input,omitempty"`
	WorkingDir string         `json:"cwd,omitempty"`
}

func (a *Agent) ParseHook(hookName string, input []byte) (*protocol.EventJSON, error) {
	if len(bytes.TrimSpace(input)) == 0 {
		return nil, nil
	}

	var payload RooHookPayload
	if err := json.Unmarshal(input, &payload); err != nil {
		return nil, fmt.Errorf("parse hook payload: %w", err)
	}

	sessionID := payload.SessionID
	if sessionID == "" {
		sessionID = payload.TaskID
	}
	if sessionID == "" {
		return nil, nil
	}

	sessionRef := transcriptPath(sessionID)
	now := time.Now().UTC().Format(time.RFC3339)

	switch hookName {
	case HookNameSessionStart, "SessionStart", "session_start":
		_ = a.PrepareTranscript(sessionRef)
		return &protocol.EventJSON{
			Type:       1,
			SessionID:  sessionID,
			SessionRef: sessionRef,
			Timestamp:  now,
		}, nil

	case HookNameTurnStart, "UserPromptSubmit", "turn_start":
		prompt := payload.Prompt
		if prompt == "" {
			prompt = payload.Message
		}
		return &protocol.EventJSON{
			Type:       2,
			SessionID:  sessionID,
			SessionRef: sessionRef,
			Prompt:     prompt,
			Timestamp:  now,
		}, nil

	case HookNameTurnEnd, "Stop", "turn_end":
		_ = a.PrepareTranscript(sessionRef)
		return &protocol.EventJSON{
			Type:       3,
			SessionID:  sessionID,
			SessionRef: sessionRef,
			Timestamp:  now,
		}, nil

	case HookNameCompaction, "compaction":
		return &protocol.EventJSON{
			Type:       4,
			SessionID:  sessionID,
			SessionRef: sessionRef,
			Timestamp:  now,
		}, nil

	case HookNameSessionEnd, "SessionEnd", "session_end":
		_ = a.PrepareTranscript(sessionRef)
		return &protocol.EventJSON{
			Type:       5,
			SessionID:  sessionID,
			SessionRef: sessionRef,
			Timestamp:  now,
		}, nil

	default:
		return nil, nil
	}
}

func (a *Agent) InstallHooks(localDev bool, force bool) (int, error) {
	repoRoot := protocol.RepoRoot()
	rooDir := filepath.Join(repoRoot, hooksRelDir)
	if err := os.MkdirAll(rooDir, 0o755); err != nil {
		return 0, err
	}

	hooksFile := filepath.Join(repoRoot, hooksRelFile)
	if !force {
		if data, err := os.ReadFile(hooksFile); err == nil {
			if strings.Contains(string(data), hooksMarker) {
				return 0, nil
			}
		}
	}

	config := map[string]interface{}{
		"_comment": hooksMarker,
		"hooks": map[string]interface{}{
			"UserPromptSubmit": []map[string]string{
				{"matcher": "*", "type": "command", "command": "entire hooks roo turn-start"},
			},
			"Stop": []map[string]string{
				{"matcher": "*", "type": "command", "command": "entire hooks roo turn-end"},
			},
			"SessionStart": []map[string]string{
				{"matcher": "*", "type": "command", "command": "entire hooks roo session-start"},
			},
			"SessionEnd": []map[string]string{
				{"matcher": "*", "type": "command", "command": "entire hooks roo session-end"},
			},
		},
	}

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return 0, err
	}

	if err := atomicWriteFile(hooksFile, data, 0o644); err != nil {
		return 0, err
	}
	return 4, nil
}

func (a *Agent) UninstallHooks() error {
	repoRoot := protocol.RepoRoot()
	hooksFile := filepath.Join(repoRoot, hooksRelFile)
	if data, err := os.ReadFile(hooksFile); err == nil {
		if strings.Contains(string(data), hooksMarker) {
			return os.Remove(hooksFile)
		}
	}
	return nil
}

func (a *Agent) AreHooksInstalled() bool {
	repoRoot := protocol.RepoRoot()
	hooksFile := filepath.Join(repoRoot, hooksRelFile)
	data, err := os.ReadFile(hooksFile)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), hooksMarker)
}
